const idsKeys: { [key: string]: string } = {
"B":"imgUrl",
"C": "sinner",
"D": "name",
"E":"rarity",
"F": "season",
"G":"sin1",
"H":"sin2",
"I":"sin3",
"J":"sinGuard",
"K":"dmgType1",
"L":"dmgType2",
"M":"dmgType3",
"N":"guardType",
"O":"idTier",
"P":"passive1Tier",
"Q":"passive2Tier",
"R":"sinPassive1",
"S":"countPassive1",
"T":"sinPassive2",
"U":"countPassive2",
"V":"slash",
"W":"pierce",
"X":"blunt",
"Y":"status",
"Z":"releaseDate",

};

export {idsKeys}